const data = {
  RECORDS: [
    {
      id: 12,
      name: 'Prince William',
      img: 'f14',
      gender: 'male',
      mid: 8,
      fid: 7,
      title: 'Duch of Cambridge',
      spouse: '{13}',
      display: 't',
    },
    {
      id: 13,
      name: 'Catherine',
      img: 'f13',
      gender: 'female',
      mid: null,
      fid: null,
      title: 'Duchess of Cambridge',
      spouse: null,
      display: 't',
    },
    {
      id: 16,
      name: 'Prince George',
      img: 'f17',
      gender: 'male',
      mid: 13,
      fid: 12,
      title: null,
      spouse: null,
      display: 't',
    },
    {
      id: 17,
      name: 'Princess Charlotte',
      img: 'f18',
      gender: 'female',
      mid: 13,
      fid: 12,
      title: null,
      spouse: null,
      display: 't',
    },
    {
      id: 2,
      name: 'Queen Elizabeth',
      img: 'f2',
      gender: 'female',
      mid: null,
      fid: null,
      title: 'The Queen Mother',
      spouse: null,
      display: 't',
    },
    {
      id: 4,
      name: 'Prince Philip',
      img: 'f3',
      gender: 'male',
      mid: null,
      fid: null,
      title: 'Duke of Edinburgh',
      spouse: null,
      display: 't',
    },
    {
      id: 15,
      name: 'Meghan Markle',
      img: 'f16',
      gender: 'female',
      mid: null,
      fid: null,
      title: null,
      spouse: null,
      display: 't',
    },
    {
      id: 14,
      name: 'Prince Harry',
      img: 'f15',
      gender: 'male',
      mid: 8,
      fid: 7,
      title: null,
      spouse: '{15}',
      display: 't',
    },
    {
      id: 6,
      name: 'Camila',
      img: 'f7',
      gender: 'female',
      mid: null,
      fid: null,
      title: 'Duchess of Cornwall',
      spouse: null,
      display: 't',
    },
    {
      id: 18,
      name: 'Prince Louise',
      img: 'f19',
      gender: 'male',
      mid: 13,
      fid: 12,
      title: null,
      spouse: null,
      display: 't',
    },
    {
      id: 8,
      name: 'Diana',
      img: 'f9',
      gender: 'female',
      mid: null,
      fid: null,
      title: 'Princess of Wales',
      spouse: null,
      display: 't',
    },
    {
      id: 20,
      name: 'King George VI',
      img: 'f1',
      gender: 'male',
      mid: null,
      fid: null,
      title: 'God Father',
      spouse: '{2}',
      display: 't',
    },
    {
      id: 21,
      name: 'Queen Elizabeth II',
      img: 'f5',
      gender: 'female',
      mid: 2,
      fid: 20,
      title: null,
      spouse: '{4}',
      display: 't',
    },
    {
      id: 11,
      name: 'Prince Edward',
      img: 'f12',
      gender: 'male',
      mid: 21,
      fid: 4,
      title: 'Earl of Wessex',
      spouse: null,
      display: 't',
    },
    {
      id: 10,
      name: 'Prince Andrew',
      img: 'f11',
      gender: 'male',
      mid: 21,
      fid: 4,
      title: 'Duke of York',
      spouse: null,
      display: 't',
    },
    {
      id: 9,
      name: 'Anne',
      img: 'f10',
      gender: 'female',
      mid: 21,
      fid: 4,
      title: 'Princess Royal',
      spouse: null,
      display: 't',
    },
    {
      id: 7,
      name: 'Charles',
      img: 'f8',
      gender: 'male',
      mid: 21,
      fid: 4,
      title: 'Prince of Wales',
      spouse: '{6,8}',
      display: 't',
    },
    {
      id: 22,
      name: 'Princess Margaret',
      img: 'f6',
      gender: 'female',
      mid: 2,
      fid: 20,
      title: null,
      spouse: null,
      display: 't',
    },
  ],
};

function assignids(data) {
  const newData = JSON.parse(JSON.stringify(data)); // Clone the data

  newData.RECORDS.forEach((record) => {
    const id = Date.now(); // Generate a unique timestamp
    record.id = id.toString();
  });

  return newData;
}

const dataIds = assignids(data);
console.log(JSON.stringify(dataIds));
